[[pages]]
path = "main.py"
name = "TextViz Studio Homepage"
icon = "ğŸ "

[[pages]]
path = "./apps/keywords/keywords.py"
name = "Text2Keywords"
icon = "ğŸ·ï¸"

[[pages]]
path = "./apps/topic_modelling/topic_modelling.py"
name = "Text2Topics"
icon = "ğŸ—‚ï¸"
